#!/bin/sh
#
# Very simple session manager for fbpanel
#

if [ -e /etc/profile ]; then
    . /etc/profile
fi

test -e /etc/rc.d/init.d/switchev && /etc/rc.d/init.d/switchev restart 2>/dev/null >/dev/null

if [ -f $HOME/.fbpanel/use_rox ]; then
    DESKTOP=rox
else
    DESKTOP=matchbox
fi

# Uncomment below to enable parsing of debian menu entrys
# export MB_USE_DEB_MENUS=1 

if [ ! -d $HOME/Choices/common ]; then
    mkdir -p $HOME/Choices/common
fi

if [ -f $HOME/Choices/lightnpower.cfg -a -e /usr/bin/lightnpower.py ]; then
    sudo lightnpower.py --loadandquit 2>/dev/null
fi

if [ -f /usr/bin/gconfd-2 ]; then
    /usr/bin/gconfd-2 15 &
fi

HARDWARE=`cat /proc/cpuinfo | grep 'Hardware' | cut -d':' -f2 | cut -d' ' -f3`
echo "pdaXrom [${HARDWARE}]"

test -f /etc/X11/kb/${HARDWARE}/xmodmap && xmodmap /etc/X11/kb/${HARDWARE}/xmodmap

test -f /etc/X11/kb/userdefined.xmodmap && xmodmap /etc/X11/kb/userdefined.xmodmap

if [ "`date +%Y`" = "1970" ]; then
    test -f /etc/rc.d/init.d/atd && /etc/rc.d/init.d/atd stop 2>/dev/null >/dev/null
    sudo datentime.py 2>/dev/null
    sudo hwclock --systohc
    test -f /etc/rc.d/init.d/atd && /etc/rc.d/init.d/atd start 2>/dev/null >/dev/null
fi

makefbmenu

#openbox 2>/dev/null >/dev/null &

#test -f /etc/sysconfig/clamshell/portrait.sh && /etc/sysconfig/clamshell/portrait.sh
#test -f /etc/sysconfig/clamshell/portrait.sh && /etc/sysconfig/clamshell/portrait.sh
eval "fbpanel" 2>/dev/null >/dev/null &
#eval "matchbox-panel" 2>/dev/null >/dev/null &
sleep 3
test -f /etc/sysconfig/clamshell/landscape.sh && /etc/sysconfig/clamshell/landscape.sh
    
case $DESKTOP in
    rox)
	ROX=`which rox`
	test $ROX && $ROX --pinboard=mypin 2>/dev/null >/dev/null
	;;
    *)
	;;
esac

touch /tmp/.mb-restart

while [ -f /tmp/.mb-restart ];
do
    rm -f /tmp/.mb-restart

    case $DESKTOP in
	matchbox)
	    MATCHBOX=`which matchbox-desktop`
	    if [ ! "x$MATCHBOX" = "x" ]; then
		if [ -f $HOME/.matchbox/mb-desktop-background ]; then
		    MBBGND=`cat $HOME/.matchbox/mb-desktop-background`
		else
		    MBBGND=""
		fi
		eval "$MATCHBOX $MBBGND" 2>/dev/null >/dev/null &
	    fi
	    ;;
	*)
	    ;;
    esac
    test -e /usr/X11R6/bin/ax && /usr/X11R6/bin/ax
    test -e /usr/bin/unclutter && /usr/bin/unclutter -idle 5 &

    # these are only temporary until the fbpanel plugins are fixed
    if [ -f $HOME/.fbpanel/fbdock ]; then
      for x in `cat $HOME/.fbpanel/fbdock` 
      do
        $x 2>/dev/null >/dev/null & 
      done
    fi

    openbox 2>/dev/null >/dev/null
done

GCONF2_PID=`pidof gconfd-2`
if [ ! "$GCONF2_PID" = "" ]; then
    kill $GCONF2_PID
fi
