#!/bin/sh
#

. /etc/init.d/functions

NAME=xstart
DAEMON=/usr/bin/startx

test -e $DAEMON || exit 0

case "$1" in
  start)
	log_begin_msg -n "Starting X11"
	export HOME=/home
	cd
	test -e /etc/profile && . /etc/profile
	start-stop-daemon -S -x "$DAEMON" -q -b >/dev/null 2>/dev/null
	log_end_msg $?
	sleep 2
	;;
  stop)
	log_begin_msg -n "Stopping X11"
	killall X >/dev/null 2>/dev/null
	log_end_msg $?
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;
esac

exit 0
