. $RULES_DIR/openbox.sh

#. $RULES_DIR/pekwm.sh

#. $RULES_DIR/Xdialog.sh

#. $RULES_DIR/idesk.sh

#
# grab X11 screen
#
. $RULES_DIR/imlib2.sh
. $RULES_DIR/giblib.sh
. $RULES_DIR/scrot.sh

#
# firefox and friends
#
. $RULES_DIR/host_findutils.sh
. $RULES_DIR/host_libIDL.sh
. $RULES_DIR/libIDL.sh
#. $RULES_DIR/firefox.sh
. $RULES_DIR/firefox-3.5.sh

#
# skipstone-gecko
#
#. $RULES_DIR/skipstone-gecko.sh

#
# webkit
#
#. $RULES_DIR/sqlite.sh
#. $RULES_DIR/libtasn1.sh
#. $RULES_DIR/libgpg-error.sh
#. $RULES_DIR/libgcrypt.sh
#. $RULES_DIR/gnutls.sh
#. $RULES_DIR/curl.sh
#. $RULES_DIR/libxslt.sh
#. $RULES_DIR/host_icu4c.sh
#. $RULES_DIR/icu4c.sh
#. $RULES_DIR/WebKit.sh

#
# midori
#
#. $RULES_DIR/libunique.sh
#. $RULES_DIR/libsoup.sh
#. $RULES_DIR/midori.sh

#
# skipstone
#
#. $RULES_DIR/skipstone.sh

#
# pidgin and friends
#
. $RULES_DIR/libtasn1.sh
. $RULES_DIR/libgpg-error.sh
. $RULES_DIR/libgcrypt.sh
. $RULES_DIR/gnutls.sh
. $RULES_DIR/pidgin.sh

#
# xchat
#
. $RULES_DIR/libsexy.sh
. $RULES_DIR/xchat.sh

#
# transmission
#
. $RULES_DIR/curl.sh
. $RULES_DIR/transmission.sh

#
# audacious
#
. $RULES_DIR/libmowgli.sh
. $RULES_DIR/mcs.sh
. $RULES_DIR/libsamplerate.sh
. $RULES_DIR/audacious.sh
. $RULES_DIR/libmad.sh
. $RULES_DIR/gettext.sh
. $RULES_DIR/neon.sh
. $RULES_DIR/audacious-plugins.sh

#
# mplayer
#

. $RULES_DIR/mplayer.sh
. $RULES_DIR/clearplayer.sh
