. $RULES_DIR/bzip2.sh
. $RULES_DIR/libjpeg.sh
. $RULES_DIR/libpng.sh
. $RULES_DIR/uuid.sh
. $RULES_DIR/openssl.sh
. $RULES_DIR/expat.sh
. $RULES_DIR/freetype.sh
. $RULES_DIR/fontconfig.sh
. $RULES_DIR/libxml2.sh
. $RULES_DIR/host_gettext.sh
. $RULES_DIR/host_glib2.sh
. $RULES_DIR/glib2.sh

#
# cups
#
. $RULES_DIR/libtasn1.sh
. $RULES_DIR/libgpg-error.sh
. $RULES_DIR/libgcrypt.sh
. $RULES_DIR/gnutls.sh
. $RULES_DIR/cups.sh
