diff -Nur qemu-0.9.1/Makefile qemu-0.9.1-new/Makefile
--- qemu-0.9.1/Makefile	2008-01-07 01:38:41.000000000 +0600
+++ qemu-0.9.1-new/Makefile	2009-01-11 12:30:58.000000000 +0600
@@ -140,7 +140,9 @@
 
 # dyngen host tool
 dyngen$(EXESUF): dyngen.c
-	$(HOST_CC) $(CFLAGS) $(CPPFLAGS) $(BASE_CFLAGS) -o $@ $^
+	$(HOST_CC) $(CFLAGS) $(CPPFLAGS) -o $@ $^
+
+#	$(HOST_CC) $(CFLAGS) $(CPPFLAGS) $(BASE_CFLAGS) -o $@ $^
 
 clean:
 # avoid old build problems by removing potentially incorrect old files
