#! /bin/bash
#
# template          Template apm script
#
# description: 
#



# See how we were called.
  
suspend() {
  return 0
}

resume() {
  return 0
}	


case "$1" in
  suspend)
  	suspend
	;;
  resume)
  	resume
	;;
  *)
	echo "Usage: $0 {suspend|resume}"
	exit 1
esac

exit $?
