#!/bin/sh

. /etc/init.d/functions

NAME=syslogd

SYSLOGD=/sbin/syslogd
SYSLOGD_ARGS="-S"
KLOGD=/sbin/klogd

case "$1" in
  start)
	log_begin_msg -n "Starting syslogd"
	start-stop-daemon -S -q -x "$SYSLOGD" -- $SYSLOGD_ARGS
	log_end_msg $?
	log_begin_msg -n "Starting klogd"
	start-stop-daemon -S -q -x "$KLOGD"
	log_end_msg $?
	exit 0
	;;
  stop)
	log_begin_msg -n "Stopping klogd"
	start-stop-daemon -K -q -x "$KLOGD"
	log_end_msg $?
	log_begin_msg -n "Stopping syslogd"
	start-stop-daemon -K -q -x "$SYSLOGD"
	log_end_msg $?
	exit 0;
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;
esac

exit 0
