--- a/Makefile-	2010-12-04 18:00:41.839400361 +0600
+++ a/Makefile	2010-12-04 18:00:49.969420472 +0600
@@ -1,7 +1,7 @@
 # Specify KDIR on cmd line, example:
 # make omap2 ARCH=arm CROSS_COMPILE=<path to arm-eabi-> KDIR=<path to kernel>
 
-EXTRA_CFLAGS = -I/usr/include
+EXTRA_CFLAGS =
 
 obj-m	:= psfreedom.o 
 
