#!/bin/sh
#

. /etc/init.d/functions

NAME=alsa-utils

case "$1" in
  start)
	log_begin_msg -n "Restoring ALSA settings"
	alsactl restore >/dev/null 2>/dev/null
	log_end_msg $?
	;;
  stop)
	log_begin_msg -n "Storing ALSA settings"
	alsactl store
	log_end_msg $?
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;
esac

exit 0
