#!/bin/sh

export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

[ -z "${COLUMNS:-}" ] && COLUMNS=30 #80

if [ -z "${BOOTUP:-}" ]; then
    if [ -f /etc/sysconfig/init ]; then
	. /etc/sysconfig/init
    else
	BOOTUP=color
	RES_COL=60
	MOVE_TO_COL="echo -en \\033[${RES_COL}G"
	SETCOLOR_SUCCESS="echo -en \\033[1;32m"
	SETCOLOR_FAILURE="echo -en \\033[1;31m"
	SETCOLOR_WARNING="echo -en \\033[1;33m"
	SETCOLOR_NORMAL="echo -en \\033[0;39m"
	LOGLEVEL=1
    fi
fi

echo_passed() {
    if [ -z "$SILENT" ] ; then
	[ "$BOOTUP" = "color" ] && $MOVE_TO_COL
	echo -n "["
	[ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
	echo -n $"PASSED"
	[ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
	echo -n "]"
	echo -ne "\r"
    fi
    return 1
}

echo_success() {
    if [ -z "$SILENT" ] ; then
	[ "$BOOTUP" = "color" ] && $MOVE_TO_COL
	echo -n "[  "
	[ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
	echo -n "OK"
	[ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
	echo -n "  ]"
	echo -ne "\r"
    fi
    return 0
}

echo_failure() {
    if [ -z "$SILENT" ] ; then
	[ "$BOOTUP" = "color" ] && $MOVE_TO_COL
	echo -n "["
	[ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
	echo -n "FAILED"
	[ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
	echo -n "]"
	echo -ne "\r"
    fi
    return 1
}

log_begin_msg() {
    if [ -z "$SILENT" ] ; then
        if [ "$1" = "-n" ] ; then
	    shift
	    echo -n $*
        else
	    echo $*
        fi
    fi
}

log_end_msg() {
    if [ -z "$SILENT" ] ; then
	if [ "$1" = "0" ]; then
	    echo_success
	else
	    echo_failure
	fi
	echo
    fi
}
