#!/bin/sh
#

. /etc/init.d/functions

if [ -e /etc/default/locale ]; then
    . /etc/default/locale
fi

NAME=genlocale

gen_locale() {
    if [ "$LANG" = "" ]; then
	return
    fi
    local L=${LANG/.*}
    local C=${LANG/*.}
    if [ "$C" = "UTF-8" ]; then
	C="utf8"
    fi
    if [ ! -e /usr/lib/locale/$L.$C ]; then
	log_begin_msg -n "Generating locale $LANG"
	localedef -c --no-archive -i $L -f ${LANG/*.} $LANG
	log_end_msg $?
    fi
}

case "$1" in
  start)
	gen_locale
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start}" >&2
	exit 1
	;;
esac

exit 0
