#! /bin/sh
#
# hal		Start the Daemon that stores device informations
#		for the Hardware abstraction layer
#
#		Written by Martin Waitz based on skeleton code
#		written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian 
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#

. /etc/init.d/functions

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/hald
PIDDIR=/var/run/hald
PIDFILE=$PIDDIR/hald.pid
NAME=hald
DAEMONUSER=haldaemon
DESC="Hardware abstraction layer"

test -x $DAEMON || exit 0

chown -R $DAEMONUSER:$DAEMONUSER /var/cache/hald /var/run/hald

set -e

do_start() {
  if [ ! -d $PIDDIR ]; then
    mkdir -p $PIDDIR
    chown $DAEMONUSER:$DAEMONUSER $PIDDIR
  fi
	log_begin_msg -n "Starting $DESC" "$NAME"
	start-stop-daemon --start --pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS
	log_end_msg $?
}

do_stop() {
	log_begin_msg -n "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--exec $DAEMON 
	log_end_msg $?
}

case "$1" in
  start)
    do_start
	;;
  stop)
    do_stop
	;;
  restart|force-reload)
  do_stop
	sleep 5
  do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
