#!/bin/sh

. /etc/init.d/functions

DAEMON="/usr/sbin/in.tftpd"

test -e $DAEMON || exit 0

TFTP_ROOT=/var/lib/tftpboot
DAEMON_OPTS="-l $TFTP_ROOT"

test -d "$TFTP_ROOT" || mkdir -p "$TFTP_ROOT"

case "${1}" in
        start)
                log_begin_msg -n "Starting tftp-hpa"
                start-stop-daemon --start --quiet --exec $DAEMON -- $DAEMON_OPTS
                log_end_msg $?
                ;;

        stop)
                log_begin_msg -n "Stopping tftp-hpa"
                start-stop-daemon --stop --quiet --exec $DAEMON
                log_end_msg $?
                ;;

        restart)
                ${0} stop
                sleep 1
                ${0} start
                ;;

        *)
                echo "Usage: ${0} {start|stop|restart|status}"
                exit 1
                ;;
esac
