#!/bin/bash
FFDIR="/usr/bin"
FIREFOX="$FFDIR/mozilla.run"
#OPENMOZ="new-tab"
OPENMOZ="new-window"
RETVAL=""
$FIREFOX -remote "ping ()" > /dev/null 2>&1
RETVAL=$?
if [ "$RETVAL" = "2" ]; then
    $FIREFOX $1
    exit
fi
if [ -z "$1" ]; then
    exec $FIREFOX -remote "openurl (,$OPENMOZ)"
    exit
fi
exec $FIREFOX -remote "openurl ($1,$OPENMOZ)"
