#!/bin/sh
#
# usbcontrol 1.0 2001/8/10 21:03:45 (Hideki Hayami)
#
# USB drivers settings
#
# The first argument should be either 'serial', 'net' or 'remove'.
#

ACTION=$1
KERNEL_VER=`/bin/uname -r`
MODULE_PATH=/lib/modules/$KERNEL_VER/kernel/drivers/usb/device
MODULE_MONITOR=usbdmonitor

checkAndRemove()
{
	if grep -q $MODULE_MONITOR /proc/modules ; then
		# unloading monitor generates hotplug unload event
		/sbin/rmmod $MODULE_MONITOR
	fi
}

# Record ACTION for use by /etc/hotplug/usbd.agent
echo $ACTION > /etc/hotplug/usbd.ftype

case "$ACTION" in
'serial' | 'net')
	checkAndRemove
	/sbin/insmod $MODULE_PATH/$MODULE_MONITOR.o
	;;
'remove')
	checkAndRemove
	;;
esac

exit 0
