#
# we use mcookie from this package
#
. $RULES_DIR/util-linux.sh

#
# xorg xapps
#

. $RULES_DIR/xbitmaps.sh
. $RULES_DIR/xorg-rgb.sh
. $RULES_DIR/xorg-xhost.sh
. $RULES_DIR/xorg-xinit.sh
. $RULES_DIR/xorg-xsetroot.sh
. $RULES_DIR/xorg-xvinfo.sh
. $RULES_DIR/xorg-xset.sh
. $RULES_DIR/xorg-xrdb.sh
. $RULES_DIR/xorg-xauth.sh
. $RULES_DIR/xorg-iceauth.sh
. $RULES_DIR/xorg-xprop.sh
. $RULES_DIR/xorg-xrandr.sh
. $RULES_DIR/xorg-mkfontdir.sh
. $RULES_DIR/xorg-mkfontscale.sh
. $RULES_DIR/xorg-xkbcomp.sh
. $RULES_DIR/xorg-setxkbmap.sh
. $RULES_DIR/xorg-xev.sh

#. $RULES_DIR/xorg-xdm.sh
#. $RULES_DIR/xorg-xclock.sh
#. $RULES_DIR/xorg-xeyes.sh
#. $RULES_DIR/xorg-twm.sh
#. $RULES_DIR/xorg-xterm.sh
