// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "netconfig.h"
#include <stdlib.h>
#include "netdevices.h"

fltk::Browser *devList=(fltk::Browser *)0;

fltk::Button *quit=(fltk::Button *)0;

static void cb_quit(fltk::Button*, void*) {
  exit(0);
}

#include <fltk/run.h>

int main (int argc, char **argv) {

  fltk::Window* w;
   {fltk::Window* o = new fltk::Window(335, 215);
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {fltk::Browser* o = devList = new fltk::Browser(5, 10, 251, 196);
      add_devices();
    }
    new fltk::Button(265, 10, 60, 25, "Edit");
     {fltk::Button* o = quit = new fltk::Button(260, 180, 65, 25, "Quit");
      o->callback((fltk::Callback*)cb_quit);
    }
    o->end();
    o->resizable(o);
  }
  w->show(argc, argv);
  return  fltk::run();
}
