diff -Nur MPlayer-1.0pre8.orig/Makefile MPlayer-1.0pre8/Makefile
--- MPlayer-1.0pre8.orig/Makefile	2006-06-11 18:35:47.000000000 +0000
+++ MPlayer-1.0pre8/Makefile	2006-07-04 09:36:52.000000000 +0000
@@ -87,7 +87,7 @@
           $(SGIAUDIO_LIB) \
           $(POLYP_LIB) \
 
-CODEC_LIBS = $(AV_LIB) \
+CODEC_LIBS = \
              $(FAME_LIB) \
              $(MAD_LIB) \
              $(VORBIS_LIB) \
@@ -389,7 +389,7 @@
     ifeq ($(TARGET_WIN32),yes)
 	windres -o osdep/mplayer-rc.o osdep/mplayer.rc
     endif
-	$(CC) $(CFLAGS) -o $(PRG) $(OBJS_MPLAYER) $(LIBS_MPLAYER)
+	$(CC) $(CFLAGS) -o $(PRG) $(OBJS_MPLAYER) $(LIBS_MPLAYER) $(AV_LIB)
 
 mplayer.exe.spec.c: libmpcodecs/libmpcodecs.a
 	winebuild -fPIC -o mplayer.exe.spec.c -exe mplayer.exe -mcui \
@@ -426,7 +426,7 @@
                 $(LIBC_LIB) \
 
 $(PRG_MENCODER): $(MENCODER_DEP)
-	$(CC) $(CFLAGS) -o $(PRG_MENCODER) $(OBJS_MENCODER) $(LIBS_MENCODER)
+	$(CC) $(CFLAGS) -o $(PRG_MENCODER) $(OBJS_MENCODER) $(LIBS_MENCODER) $(AV_LIB)
 endif
 
 codecs.conf.h: $(PRG_CFG) etc/codecs.conf
@@ -439,7 +439,7 @@
 
 $(PRG_CFG): codec-cfg.c codec-cfg.h help_mp.h
 	$(HOST_CC) $(HOST_CFLAGS) -I. codec-cfg.c -o $(PRG_CFG) \
-	-DCODECS2HTML $(EXTRA_LIB) $(EXTRA_INC)
+	-DCODECS2HTML
 
 install: $(ALL_PRG)
 ifeq ($(VIDIX),yes)
