// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef netconfig_h
#define netconfig_h
#include <fltk/Window.h>
#include <fltk/Browser.h>
extern fltk::Browser* devList;
#include <fltk/Button.h>
extern fltk::Button* quit;
#endif
