#!/bin/sh
#
# /etc/init.d/rcS
#
# $Id: rcS 7022 2007-02-28 14:17:06Z jbe $
#

echo -n "mounting filesystems..."
mount -a 2>/dev/null
echo "done."

if mount | grep /dev/root | grep cramfs >/dev/null ; then
    echo "move /etc to ram..."
    tar c /etc 2>/dev/null | tar x -C /tmp
    echo "done."
    mount -o bind /tmp/etc /etc
    echo "move /var to ram..."
    tar c /var 2>/dev/null | tar x -C /tmp
    echo "done."
    mount -o bind /tmp/var /var
fi

# modprobe ppp_async
# loadkmap < /etc/boottime.kmap

# set hostname
test -e /etc/hostname && hostname -F /etc/hostname

echo "running rc.d services..."
run-parts -a start /etc/rc.d
