#! /bin/sh
. /etc/udev/udev.conf

sysfs_dir=/sys

make_extra_nodes() {
    [ -e /etc/udev/links.conf ] || return
    grep '^[^#]' /etc/udev/links.conf | \
    while read type name arg1; do
	[ "$type" -a "$name" -a ! -e "/dev/$name" -a ! -L "/dev/$name" ] ||continue
	case "$type" in
    	    L) ln -s $arg1 /dev/$name ;;
    	    D) mkdir -p /dev/$name ;;
    	    M) mknod /dev/$name $arg1 ;;
    	    *) echo "links.conf: unparseable line ($type $name $arg1)" ;;
	esac
    done
}

if [ ! -d $sysfs_dir/kernel ]; then
	echo "error: sysfs not mounted"
	exit 1
fi

echo "mounting... tmpfs at $udev_root"
mount -n -t tmpfs tmpfs $udev_root -o mode=755

echo /sbin/udevsend > /proc/sys/kernel/hotplug 

[ -d /proc/1 ] || mount -n /proc
echo -n "Creating initial device nodes..."
/sbin/udevstart
echo "done."

echo "creating static nodes"
make_extra_nodes
echo "done"
# We can only mount /dev/pts after initialising udev
if [ -d "/dev/pts" ]; then
	mount /dev/pts
fi
echo "udev startup is finished"
exit 0
