#!/bin/sh
#
# (c) pdaXrom team, 2006
# http://www.pdaXrom.org
#

convert_desktop_file() {
    echo "item {"
awk '
BEGIN { 
    FS="=";
    sn="";
    name="";
    image="";
} 
/^Name/ && !/\[/ {name = $2}
/^Icon/ {image = $2}
/^Exec/ {exe = $2}
/^StartupNotify/ {if ( $2 == "True" || $2 == "true") sn = "yes"}
END {
    print "name = " name;
    print "image = " image;
    if (exe != "")
	if (sn != "")
	    print "actionsn = " exe;
	else
	    print "action = " exe;
}' $1
    echo "}"
}

test -d ~/.fbpanel || mkdir ~/.fbpanel

rm -f 	~/.fbpanel/AudioVideo.inc	\
	~/.fbpanel/Network.inc 	\
	~/.fbpanel/Office.inc	\
	~/.fbpanel/Graphics.inc 	\
	~/.fbpanel/Games.inc	\
	~/.fbpanel/Settings.inc 	\
	~/.fbpanel/Applications.inc \
	~/.fbpanel/Panel.inc

touch 	~/.fbpanel/AudioVideo.inc	\
	~/.fbpanel/Network.inc 	\
	~/.fbpanel/Office.inc	\
	~/.fbpanel/Graphics.inc 	\
	~/.fbpanel/Games.inc	\
	~/.fbpanel/Settings.inc 	\
	~/.fbpanel/Applications.inc \
	~/.fbpanel/Panel.inc

for file in /usr/share/applications/* /usr/local/share/applications/*; do
    if [ -e $file ]; then
	TYPE=`awk -F'=' '/^Categories/ {print $2}' $file`
	case $TYPE in 
	    *AudioVideo*)
		    convert_desktop_file $file >> ~/.fbpanel/AudioVideo.inc
		;;
	    *Network*)
		    convert_desktop_file $file >> ~/.fbpanel/Network.inc
		;;
	    *Office*|*WordProcessor*)
		    convert_desktop_file $file >> ~/.fbpanel/Office.inc
		;;
	    *Graphics*)
		    convert_desktop_file $file >> ~/.fbpanel/Graphics.inc
		;;
	    *Games*)
		    convert_desktop_file $file >> ~/.fbpanel/Games.inc
		;;
	    *Settings*)
		    convert_desktop_file $file >> ~/.fbpanel/Settings.inc
		;;
	    *Panel*)
		    convert_desktop_file $file >> ~/.fbpanel/Panel.inc
		;;
	    *)
		    convert_desktop_file $file >> ~/.fbpanel/Applications.inc
		;;
	esac
    fi
done
