. $RULES_DIR/openbox.sh

#. $RULES_DIR/Xdialog.sh

#. $RULES_DIR/idesk.sh

#. $RULES_DIR/rdesktop.sh

#
# firefox and friends
#
. $RULES_DIR/host_findutils.sh
. $RULES_DIR/host_libIDL.sh
. $RULES_DIR/libIDL.sh
. $RULES_DIR/firefox.sh

#
# skipstone-gecko
#
#. $RULES_DIR/skipstone-gecko.sh

#
# webkit
#
#. $RULES_DIR/sqlite.sh
#. $RULES_DIR/libtasn1.sh
#. $RULES_DIR/libgpg-error.sh
#. $RULES_DIR/libgcrypt.sh
#. $RULES_DIR/gnutls.sh
#. $RULES_DIR/curl.sh
#. $RULES_DIR/libxslt.sh
#. $RULES_DIR/host_icu4c.sh
#. $RULES_DIR/icu4c.sh
#. $RULES_DIR/WebKit.sh

#
# midori
#
#. $RULES_DIR/libunique.sh
#. $RULES_DIR/libsoup.sh
#. $RULES_DIR/midori.sh

#
# skipstone
#
#. $RULES_DIR/skipstone.sh

#
# pidgin and friends
#
. $RULES_DIR/libtasn1.sh
. $RULES_DIR/libgpg-error.sh
. $RULES_DIR/libgcrypt.sh
. $RULES_DIR/gnutls.sh
. $RULES_DIR/pidgin.sh

#
# xchat
#
. $RULES_DIR/libsexy.sh
. $RULES_DIR/xchat.sh

#
# Abiword and friends
#
#. $RULES_DIR/libgsf.sh
#. $RULES_DIR/libfribidi.sh
#. $RULES_DIR/libwv.sh
#. $RULES_DIR/popt.sh
#. $RULES_DIR/libglade.sh
#. $RULES_DIR/abiword.sh

#
# audacious
#
. $RULES_DIR/libmowgli.sh
. $RULES_DIR/mcs.sh
. $RULES_DIR/libsamplerate.sh
. $RULES_DIR/audacious.sh
. $RULES_DIR/libmad.sh
. $RULES_DIR/gettext.sh
. $RULES_DIR/audacious-plugins.sh
