--- s/Makefile~	2006-09-29 10:45:42.000000000 +0000
+++ s/Makefile	2006-09-29 10:45:55.000000000 +0000
@@ -48,7 +48,7 @@
 	rm -f $(MODULE_INSTALLDIR)spca5xx.ko
 	rm -f $(MODULE_INSTALLDIR2)gspca.ko
 	install -c -m 0644 gspca.ko $(MODULE_INSTALLDIR)
-	/sbin/depmod -ae
+#	/sbin/depmod -ae
 
 uninstall:
 	rm -f $(MODULE_INSTALLDIR)gspca.ko
