#!/bin/sh

for app in leafpad SciTE gvim abiword; do
  if [ -x "`which $app`" ]; then 
    exec "$app" "$@"
    exit 0
  fi
done

for app in vim mcedit vi; do
  if [ -x "`which $app`" ]; then 
    exec xterm -e "$app" "$@"
    exit 0
  fi
done

