Welcome to pdaXrom-NG live cd for Sony PlayStation 3!

Use boot menu to select video mode or edit boot
configuration 'live video=ps3fb:mode:X', setting X
to the video mode (such as 3 for 720p). 

0:auto mode
YUV 60Hz  1:480i  2:480p  3:720p  4:1080i  5:1080p
YUV 50Hz  6:576i  7:576p  8:720p  9:1080i 10:1080p
RGB 60Hz 33:480i 34:480p 35:720p 36:1080i 37:1080p
RGB 50Hz 38:576i 39:576p 40:720p 41:1080i 42:1080p
VESA     11:WXGA 12:SXGA 13:WUXGA

full screen mode: <video mode ID> + 128
dither ON mode  : <video mode ID> + 2048

If in doubt, just press Enter.
