. $RULES_DIR/openbox.sh

#. $RULES_DIR/pekwm.sh

#. $RULES_DIR/Xdialog.sh

#. $RULES_DIR/idesk.sh

#
# grab X11 screen
#
. $RULES_DIR/imlib2.sh
. $RULES_DIR/giblib.sh
. $RULES_DIR/scrot.sh

. ./sets/packages-firefox.inc

#
# skipstone-gecko
#
#. $RULES_DIR/skipstone-gecko.sh

#
# webkit
#
#. $RULES_DIR/sqlite.sh
#. $RULES_DIR/libtasn1.sh
#. $RULES_DIR/libgpg-error.sh
#. $RULES_DIR/libgcrypt.sh
#. $RULES_DIR/gnutls.sh
#. $RULES_DIR/curl.sh
#. $RULES_DIR/libxslt.sh
#. $RULES_DIR/host_icu4c.sh
#. $RULES_DIR/icu4c.sh
#. $RULES_DIR/WebKit.sh

#
# midori
#
#. $RULES_DIR/libunique.sh
#. $RULES_DIR/libsoup.sh
#. $RULES_DIR/midori.sh

#
# skipstone
#
#. $RULES_DIR/skipstone.sh

. ./sets/packages-pidgin.inc

#
# xchat
#
. $RULES_DIR/libsexy.sh
. $RULES_DIR/xchat.sh

#
# transmission
#
. $RULES_DIR/curl.sh
. $RULES_DIR/transmission.sh

#
# mplayer
#
. $RULES_DIR/SDL.sh
. $RULES_DIR/libogg.sh
. $RULES_DIR/libvorbis.sh
. $RULES_DIR/speex.sh
. $RULES_DIR/libtheora.sh
. $RULES_DIR/libv4l.sh

. $RULES_DIR/mplayer.sh
. $RULES_DIR/clearplayer.sh
