#
#
#
. $RULES_DIR/SDL.sh
. $RULES_DIR/libogg.sh
. $RULES_DIR/libvorbis.sh
. $RULES_DIR/speex.sh
. $RULES_DIR/libtheora.sh
. $RULES_DIR/libv4l.sh
. $RULES_DIR/ffmpeg.sh
. $RULES_DIR/host_yasm.sh
. $RULES_DIR/x264-snapshot.sh

#
# ekiga
#
. $RULES_DIR/ptlib.sh
. $RULES_DIR/opal.sh
. $RULES_DIR/libsigc++.sh
. $RULES_DIR/ekiga.sh

#
# linphone
#

#. $RULES_DIR/libosip2.sh
#. $RULES_DIR/libeXosip2.sh
#. $RULES_DIR/linphone.sh
