#!/bin/sh

test -f /usr/bin/sixaxisd || exit 0

. /etc/init.d/functions

DAEMON=/usr/bin/sixaxisd
DAEMON_ARGS="-mouse"

export PATH=$PATH:/usr/bin:/usr/sbin

case "$1" in
  start)
	log_begin_msg -n "Starting sixaxis bluetooth mouse emulator"
	hciconfig hci0 up
	hciconfig hci0 lm master
	hciconfig hci0 piscan

	start-stop-daemon -S -q -b -x "$DAEMON" -- $DAEMON_ARGS

	log_end_msg $?
	;;
  stop)
	log_begin_msg -n "Stopping sixaxis bluetooth mouse emulator"
	start-stop-daemon -K -q -x "$DAEMON"
	hciconfig hci0 down 2>/dev/null >/dev/null
	true
	log_end_msg $?
	;;
  *)
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;
esac

exit 0
