#!/bin/sh

PATH=/usr/sbin:/usr/bin:/sbin:/bin

killall ps3boot-udev 2>/dev/null >/dev/null

/usr/sbin/ps3boot

killall ps3boot-udev 2>/dev/null >/dev/null

mount | grep '/media/dev' | awk '{ print $3 }' | while read f; do
    umount $f && rm -rf $f
done
