#!/bin/sh

PATH=/usr/sbin:/usr/bin:/sbin:/bin

SIXAXISD_PID=

if [ -e /usr/bin/hciconfig ]; then
    /usr/bin/hciconfig hci0 up
    /usr/bin/hciconfig hci0 lm master
    /usr/bin/hciconfig hci0 piscan
    
    /usr/bin/sixaxisd &
    
    SIXAXISD_PID=$!
fi

while true ; do
    killall ps3boot-udev 2>/dev/null >/dev/null

    /usr/sbin/ps3boot

    killall ps3boot-udev 2>/dev/null >/dev/null

    mount | grep '/media/dev' | awk '{ print $3 }' | while read f; do
	umount $f && rm -rf $f
    done

    if [ -e /tmp/ps3boot.inc ]; then
	reset
	. /tmp/ps3boot.inc
	rm -f /tmp/ps3boot.inc
    else
	break
    fi
done

if [ ! "$SIXAXISD_PID" = "" ]; then
    kill -9 $SIXAXISD_PID
fi
