--- linux-2.6.27/fs/squashfs/Makefile-	2009-01-03 21:04:38.000000000 +0600
+++ linux-2.6.27/fs/squashfs/Makefile	2009-01-03 21:06:18.000000000 +0600
@@ -2,6 +2,13 @@
 # Makefile for the linux squashfs routines.
 #
 
-obj-$(CONFIG_SQUASHFS) += squashfs.o
+# the environment variables are not inherited since 2.6.23
+ifdef SQLZMA_EXTRA_CFLAGS
+EXTRA_CFLAGS += ${SQLZMA_EXTRA_CFLAGS}
+endif
+
+obj-$(CONFIG_SQUASHFS) += unlzma.o sqlzma.o squashfs.o
+unlzma-y := module.o
+sqlzma-y := uncomp.o
 squashfs-y += inode.o
 squashfs-y += squashfs2_0.o
