#!/bin/sh

. /etc/init.d/functions

DAEMON="/usr/sbin/cupsd"

test -e $DAEMON || exit 0

mkdir -p /var/spool/cups/tmp
mkdir -p /var/run/cups/certs

case "${1}" in
        start)
                log_begin_msg -n "Starting cupsd"
                start-stop-daemon --start --quiet --exec $DAEMON
                log_end_msg $?
                ;;

        stop)
                log_begin_msg -n "Stopping cupsd"
                start-stop-daemon --stop --quiet --exec $DAEMON
                log_end_msg $?
                ;;

        restart)
                ${0} stop
                sleep 1
                ${0} start
                ;;

        *)
                echo "Usage: ${0} {start|stop|restart|status}"
                exit 1
                ;;
esac
