--- s/Makefile-	2008-05-10 23:31:02.000000000 +0700
+++ s/Makefile	2008-05-10 23:31:53.000000000 +0700
@@ -40,7 +40,7 @@
 	$(call summary,LD  ,$@)
 	$(Q)$(CC) $(LDFLAGS) $(OBJ) $(EXTRAOBJ) $(LIBS) -o $@
 ifeq (0,$(DEVEL))
-	$(Q)strip $@
+	$(Q)$(STRIP) $@
 endif
 
 
--- s/plugins/Makefile-	2008-05-10 23:32:38.000000000 +0700
+++ s/plugins/Makefile	2008-05-10 23:32:49.000000000 +0700
@@ -22,7 +22,7 @@
 	$(call summary,LD  ,$@)
 	$(Q)$(CC) $(CFLAGS) $(INCS) $< -o $@
 ifeq (0,$(DEVEL))
-	$(Q)strip $@
+	$(Q)$(STRIP) $@
 endif
 
 else
--- s/systray/Makefile-	2008-05-10 23:33:19.000000000 +0700
+++ s/systray/Makefile	2008-05-10 23:33:29.000000000 +0700
@@ -17,7 +17,7 @@
 	$(call summary,LD  ,$@)
 	$(Q)$(CC) $(CFLAGS) $(INCS) $(OBJ) -o $@
 ifeq (0,$(DEVEL))
-	$(Q)strip $@
+	$(Q)$(STRIP) $@
 endif
 
 else
