#!/bin/bash

if [ -f /etc/profile ]; then
    . /etc/profile
fi

hostname archos

mount /proc
#mount /dev

chmod 644 /etc/busybox.conf


/etc/rc.d/init.d/ssh start

export HOME=/home/root
echo
echo `cat /etc/issue`
echo

/bin/bash
