#!/bin/sh
#

. /etc/init.d/functions

#exec 2>/dev/null >/dev/null

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/dropbear
NAME=dropbear
DESC="Dropbear SSH server"

if [ -z /var/run/${NAME}.init ]; then
    touch /var/run/${NAME}.init

    case "$1" in
    start)
	log_begin_msg -n "Starting $DESC "
    	start-stop-daemon -S -x "/etc/init.d/$NAME" -q -b -- start  >/dev/null 2>/dev/null
	log_end_msg $?
	exit 0
	;;
    esac
    rm -f /var/run/${NAME}.init
fi

DROPBEAR_PORT=22
DROPBEAR_EXTRA_ARGS=

#set -e

# test ! -h /var/service/dropbear || exit 0

DROPBEAR_RSAKEY_DEFAULT="/etc/dropbear/dropbear_rsa_host_key"
DROPBEAR_DSSKEY_DEFAULT="/etc/dropbear/dropbear_dss_host_key"

test -z "$DROPBEAR_BANNER" || \
  DROPBEAR_EXTRA_ARGS="$DROPBEAR_EXTRA_ARGS -b $DROPBEAR_BANNER"
test -n "$DROPBEAR_RSAKEY" || \
  DROPBEAR_RSAKEY=$DROPBEAR_RSAKEY_DEFAULT
test -n "$DROPBEAR_DSSKEY" || \
  DROPBEAR_DSSKEY=$DROPBEAR_DSSKEY_DEFAULT
test -n "$DROPBEAR_KEYTYPES" || \
  DROPBEAR_KEYTYPES="rsa dsa"

gen_keys() {
for t in $DROPBEAR_KEYTYPES; do
  case $t in
    rsa)
        test -f $DROPBEAR_RSAKEY || dropbearkey -t rsa -f $DROPBEAR_RSAKEY > /dev/null 2>/dev/null || echo -n " rsa isn't calculated"
	;;
    dsa)
        test -f $DROPBEAR_DSSKEY || dropbearkey -t dss -f $DROPBEAR_DSSKEY > /dev/null 2>/dev/null || echo -n " dss isn't calculated"
	;;
  esac
done
}

case "$1" in
  start)
	#log_begin_msg -n "Starting $DESC "
	gen_keys
	KEY_ARGS=""
	test -f $DROPBEAR_DSSKEY && KEY_ARGS="$KEY_ARGS -d $DROPBEAR_DSSKEY"
	test -f $DROPBEAR_RSAKEY && KEY_ARGS="$KEY_ARGS -r $DROPBEAR_RSAKEY"
	start-stop-daemon -S \
	  -x "$DAEMON" -- $KEY_ARGS \
	    -p "$DROPBEAR_PORT" $DROPBEAR_EXTRA_ARGS
	#log_end_msg $?
	;;
  stop)
	log_begin_msg -n "Stopping $DESC "
	start-stop-daemon -K -x "$DAEMON" -q
	log_end_msg $?
	;;
  restart|force-reload)
	log_begin_msg -n "Restarting $DESC "
	start-stop-daemon -K -x "$DAEMON" -q
	sleep 1
	KEY_ARGS=""
	test -f $DROPBEAR_DSSKEY && KEY_ARGS="$KEY_ARGS -d $DROPBEAR_DSSKEY"
	test -f $DROPBEAR_RSAKEY && KEY_ARGS="$KEY_ARGS -r $DROPBEAR_RSAKEY"
	start-stop-daemon -S \
	  -x "$DAEMON" -- $KEY_ARGS \
	    -p "$DROPBEAR_PORT" $DROPBEAR_EXTRA_ARGS
	log_end_msg $?
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
