#!/bin/sh
#
# /etc/init.d/rcS
#

. /etc/init.d/functions

if [ -e /sbin/usplash ]; then
    echo
elif [ -e /usr/bin/figlet ]; then
    figlet -t -c "pdaXrom-NG"
    figlet -t -c `uname -sm`
    echo -ne "\n\n"
fi

log_begin_msg -n "Мounting filesystems..."
mount -a 2>/dev/null
log_end_msg $?

if mount | grep ' / ' | grep -q 'squashfs' ; then
    for d in /var /etc /home /media ; do
	log_begin_msg -n "Moving $d to ram"
	tar c $d 2>/dev/null | tar x -C /tmp && mount -o bind /tmp$d $d
	log_end_msg $?
	if [ "$d" = "/var" ]; then
	    test -e /sbin/usplash && usplash -c -v &
	fi
    done
else
    log_begin_msg -n "Remounting rootfs for read/write"
    mount -o remount,rw /
    log_end_msg $?
    test -e /sbin/usplash && usplash -c -v &
fi

# Disable kernel log to console
echo "0 0 0 0" >/proc/sys/kernel/printk

# set hostname
test -e /etc/hostname && hostname -F /etc/hostname

for i in /etc/rc.d/S*; do 
    $i start
done

sleep 5

pidof usplash >/dev/null && usplash_write "QUIT"
