#!/bin/sh
#
# /etc/init.d/rcS
#

#[ -e /dev/console ] || mknod -m 0600 /dev/console c 5 1
#[ -e /dev/null    ] || mknod -m 0666 /dev/null c 1 3

echo -n "mounting filesystems..."
mount -a 2>/dev/null
echo "done."

if mount | grep /dev/root | grep squashfs >/dev/null ; then
    echo "move /etc to ram..."
    tar c /etc 2>/dev/null | tar x -C /tmp
    echo "done."
    mount -o bind /tmp/etc /etc
    echo "move /var to ram..."
    tar c /var 2>/dev/null | tar x -C /tmp
    echo "done."
    mount -o bind /tmp/var /var

    # put user dir in /tmp
    mkdir /tmp/home
    mount -o bind /tmp/home /home
    # put media dir in /tmp
    mkdir /tmp/media
    mount -o bind /tmp/media /media
else
    mount -o remount,rw /
fi

# Disable kernel log to console
echo "4 4 1 7" >/proc/sys/kernel/printk

# modprobe ppp_async
# loadkmap < /etc/boottime.kmap

# set hostname
test -e /etc/hostname && hostname -F /etc/hostname

echo "running rc.d services..."
run-parts -a start /etc/rc.d
