. $RULES_DIR/eina.sh
. $RULES_DIR/eet.sh
. $RULES_DIR/evas.sh
. $RULES_DIR/ecore.sh
. $RULES_DIR/embryo.sh
. $RULES_DIR/readline.sh
. $RULES_DIR/lua.sh
. $RULES_DIR/edje.sh
. $RULES_DIR/efreet.sh

. $RULES_DIR/host_findutils.sh
. $RULES_DIR/host_glib2.sh
. $RULES_DIR/host_expat.sh
. $RULES_DIR/host_dbus.sh
. $RULES_DIR/host_dbus-glib.sh
. $RULES_DIR/dbus.sh
. $RULES_DIR/dbus-glib.sh
. $RULES_DIR/e_dbus.sh

. $RULES_DIR/eeze.sh

. $RULES_DIR/host_lua.sh
. $RULES_DIR/host_eina.sh
. $RULES_DIR/host_eet.sh
. $RULES_DIR/host_evas.sh
. $RULES_DIR/host_ecore.sh
. $RULES_DIR/host_embryo.sh
. $RULES_DIR/host_edje.sh
. $RULES_DIR/enlightenment.sh
